---
# tasks file for python-venv
- name: Install Python3
  import_tasks: installPython.yml
  become: true

- name: Setup Venv
  import_tasks: createVenv.yml
  become: true
  # # become_method: sudo
  # become_user: "{{ adm_usr }}"