- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ ssl_loc }}/{{ hx_vhost }}.key"

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ ssl_loc }}/{{ hx_vhost }}.key"
    common_name: "{{ hx_vhost }}"
    organization_name: "{{ hx_vhost }}"
    
  register: csr

- name: Create self-signed certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ ssl_loc }}/{{ hx_vhost }}.pem"
    csr_content: "{{ csr.csr }}"
    privatekey_path: "{{ ssl_loc }}/{{ hx_vhost }}.key"
    provider: selfsigned