

- name: "Check {{ dest_dir }} Directory exists"
  stat: 
    path: "{{ dest_dir }}"
  register: out

- debug:
    var: out


- name: "Empty {{ dest_dir }} destination directory"  
  file: 
    state: absent 
    path: "{{ dest_dir }}/"
  when: out.stat.exists == true


- name: Create a directory {{ dest_dir }} if it does not exist
  ansible.builtin.file:
    path: "{{ dest_dir }}"
    state: directory
    mode: '0755'